### ISSUE TITLE
E coming out as i

### ISSUE THREAD

**Issue by kr4ez** [k0tet/morsetrainer#43]
The lady is saying e but an I with the spacing a little off is being sent.

LG G7 phone

And thank you so much for this app

**Comment by cniesen** [comment]
The app is using the text-to-speech engine that's on your phone.  For Samsung phones I found that using the Google engine produced better speech than the Samsung engine.  Maybe you can try that out.  

Otherwise you could try tweaking the spoken text to something that sounds closer to the E (see [README_WORDLIST.md](https://github.com/cniesen/morsetrainer/blob/master/README_WORDLIST.md).  Another option is to use the  [abc_nato.txt](https://github.com/cniesen/morsetrainer/tree/master/additional_word_lists) world list.

Unfortunately, there is nothing in the app that would fix that issue.
